### ISSUE TITLE
[Bug] Changed C# project to TFM 4.8 and it results in errors when running templates

### ISSUE THREAD

**Issue by Smurf-IV** [ffadrique/XFunit#2]
Using VS 17.5.2
![image](https://user-images.githubusercontent.com/2418812/227146568-df25da95-8327-4360-833c-b730243f10cb.png)

![image](https://user-images.githubusercontent.com/2418812/227146866-6d403839-fee2-4dc6-85c7-49acd961959c.png)

**Comment by ffadrique** [comment]
Hi Simon,
I have been off for a while; back again.
I am not familiar with TFM, so I cannot really say what you have changed. What is actually TFM and what does it replace?
The second sanpshot is the consequence the error in the first one, that resuls in the the actual code not being generated from the .tt file. I have seen that many time while debugging.
I have seen other questions in the thread, when we clarify the TFM change, I will address them too.
Cheers,
Fran

**Comment by Smurf-IV** [comment]
TFM = "Target Framework Moniker", it what MS call the special text inside sdk style projects to determine the target types to be built.

**Comment by ffadrique** [comment]
I have migrated the project to .NET Framework 4.8 and fixed the bug in the template. Changes commited to repository.
