### ISSUE TITLE
[Bug] Following code will not work if run from command line via unitTester

### ISSUE THREAD

**Issue by Smurf-IV** [ffadrique/XFunit#4]
![image](https://user-images.githubusercontent.com/2418812/227153991-78333f0d-6ec0-4f8d-aa7d-97d7c269cfb7.png)

There is no Visual studio, so an exception will / may be thrown !

https://stackoverflow.com/questions/27356583/getting-envdte-dte-instance-outside-visual-studio-ide

**Comment by ffadrique** [comment]
Right. I never meant to run the suite of unit tests outside VS. Note that the repository if for XFunit and unit_test_driver is just a tool to execute all unit tests. I used it for continuos integration to detect regressions and for scratch installations is meant to be used to test that installation and behaviour of XFunit is correct.

**Comment by Smurf-IV** [comment]
> I used it for continuos integration to detect regressions

This is what CI in dev-ops does and it needs to be run outside VS via VSTest or other exe / batch runner.

**Comment by ffadrique** [comment]
May be in the way you intend to use this tool, but not the way I inted to use it. Feel free to take it and adpat it s required for your need.
