### ISSUE TITLE
[Question] If I have a solution that has 30 exe (Of different project types) then what is the following going to do?

### ISSUE THREAD

**Issue by Smurf-IV** [ffadrique/XFunit#5]
![image](https://user-images.githubusercontent.com/2418812/227158819-a7a6f91a-0b6d-4f95-83c4-608c38be088a.png)

Is this going to attempt to run all exe's even if **only 1** of them is a Fortran test. 
(i.e. others are the actual massive Fortran Exe / several C# Gui's / installer(s) etc.)

**Comment by Smurf-IV** [comment]
I could have utility apps in the solution dir as well (i.e. `sign.exe` / hashers / etc) that are not built, but are needed in the solution references

**Comment by ffadrique** [comment]
This tool (unit_test_driver) was disigned to simply run the unit test in the very specific configuration provided. All unit tests have the source of the form unit_<test-name> with a corresponding executable unit_<test-name>.exe and all contained in the directory tree below utest. No other executables are expected below utest.
The template (*.tt) just scans the unit test and generate one entry for each one in unit_test_driver.generated.cs making VS aware of each of the unit tests with the [TestMethod] metacommand.
The scenarion that you consider could be adapted but I cannot really say what the behavioud would be with the tool as is.

**Comment by Smurf-IV** [comment]
> with a corresponding executable unit_.exe

Thanks for the reply.. Re the above, Our format is to have the "Dll / project" name under test, followed by `_Tests`.
So I will need a step that allows the `testName` glob to be passed in.

i/e/ please change the above to use a nuget that allows FileGlobbing, and thus will allow any format of "teststring" to be matched

**Comment by ffadrique** [comment]
Propose the changes that you need that may be considered. As said, this is a subsidiary tool just to thest the XFunit library not inteded to cover all other possible use cases.
